oracle-nosql:
  mode: local
  endpoint: "http://localhost:9050/"
  createTables: true

micronaut:
  security:
    #    authentication: bearer
    token:
      generator:
        access-token:
          expiration: 7200
      jwt:
        signatures:
          secret:
            generator:
              secret: fakeTokenForTestsDoNotTrustFooooooooooooooooooooooo

