micronaut:
  application:
    name: xivgear-account-service
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  security:
    enabled: true
    authentication: bearer
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()

  session:
    filter:
      enabled: true
  #

  server:
    host: 0.0.0.0
    cors:
      enabled: true
  openapi:
    enabled: true
  swagger:
    enabled: true
  swagger-ui:
    enabled: true

oci:
  config:
    enabled: false

oracle-nosql:
  endpoint: "https://nosql.us-sanjose-1.oci.oraclecloud.com:443/"
  mode: cloud
  compartment: ${ORACLE_CLOUD_COMPARTMENT_ID:}
  tables:
    userData:
      name: "userdata_test"
    sheets:
      name: "sheets_test"
